schema_version: 1

pipeline:
  images_root: "1_3D_images"
  manifest_dir: "radiomics_manifests"
  output_dir: "radiomics_features"
  jobs: 4

search:
  allowed_extensions:
    - ".mha"
    - ".mhd"
    - ".nrrd"
    - ".nii"
    - ".nii.gz"

# Stage 2 extraction settings.
reference_image: t1w
working_spacing_mm: [1, 1, 1]
minimum_physical_overlap_fraction: 0.10

require_complete_patients: false

bin_counts: [16,32, 64, 128]
pyfe_radius: [1,2,3]
normalize: true

intensity_scaling:
  adc:
    divide_by: 3000.0
    note: "Normalize ADC by water diffusivity reference before radiomics."

# Options: [Original], [Original, Wavelet, LoG], or all.
image_types:
  - all
# skip_image_types:
#   - LBP3D
skip_failed_image_types: true

log_sigmas: [1.0, 2.0, 3.0]
include_shape_features: true
include_benford_features: false
minimum_mask_voxels: 10

qc:
  enabled: true
  alpha: 0.45
  dpi: 120

feature_cache:
  enabled: true
  hash_file_contents: false

augmentation:
  enabled: true
  samples_per_patient: 2
  random_state: 42
  rotation_degrees:
    - [-5.0, 5.0]
    - [-5.0, 5.0]
    - [-1.0, 1.0]
  translation_mm:
    - [-5.0, 5.0]
    - [-5.0, 5.0]
    - [-5.0, 5.0]
  scale:
    - [1.0, 1.0]
    - [1.0, 1.0]
    - [1.0, 1.0]

roi:
  name: "roi_T"
  required: true
  multiple: false
  patterns:
    - "ROI_T.nrrd"
    - "roi_t.nrrd"
    - "*ROI*T*.nrrd"
    - "*TOI*T*.nrrd"
    - "*toi*T*.nrrd"
    - "*roi*T*.nrrd"
    - "*tumor*.nii"
    - "*tumor*.nii.gz"

modalities:
  t1w:
    label: "T1-weighted"
    required: true
    multiple: false
    patterns:
      - "T1w.mha"
      - "T1w.nrrd"
      - "*T1w*.mha"
      - "*T1w*.nrrd"
      - "*T1*.mha"
      - "*T1*.nrrd"
      - "*T1w*.nii"
      - "*T1w*.nii.gz"
      - "*T1*.nii"
      - "*T1*.nii.gz"

    exclude_patterns:
      - "*CONT*"
      - "*contrast*"
      - "*post*"
  t1wc:
    label: "T1-weighted contrast-enhanced"
    required: true
    multiple: false
    patterns:
      - "T1w_CONT.mha"
      - "T1w_CONT.nrrd"
      - "*T1*CONT*.mha"
      - "*T1*CONT*.nrrd"
      - "*T1*contrast*.mha"
      - "*T1*contrast*.nrrd"
      - "*T1*post*.mha"
      - "*T1*post*.nrrd"
      - "*T1*CONT*.nii"
      - "*T1*CONT*.nii.gz"
      - "*T1*contrast*.nii"
      - "*T1*contrast*.nii.gz"


  t2w:
    label: "T2-weighted"
    required: true
    multiple: false
    patterns:
      - "T2w.mha"
      - "T2w.nrrd"
      - "*T2w*.mha"
      - "*T2w*.nrrd"
      - "*T2*.mha"
      - "*T2*.nrrd"
      - "*T2w*.nii"
      - "*T2w*.nii.gz"
      - "*T2*.nii"
      - "*T2*.nii.gz"


  adc:
    label: "ADC map"
    required: true
    multiple: false
    patterns:
      - "ADC.mha"
      - "ADC.nrrd"
      - "*ADC*.mha"
      - "*ADC*.nrrd"
      - "*ADC*.nii"
      - "*ADC*.nii.gz"


radiomics:
  # Label value inside ROI_T.nrrd to use as the tumor mask.
  label: 1
